blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/clearwaterkzk/kaggle_titanic/issues/new?template=custom.md&projects=clearwaterkzk%2Fkaggle_titanic%2F1&labels=kaggle_titanic
